// Claude writes down what a session is about, and this is how a hook reads it.
//
// It is in this program rather than in core because every word of it is
// Claude's: the file and the line type (R10). Core is handed a name and never
// learns which of three places produced it.
package main

import (
	"bytes"
	"encoding/json"
	"os"
	"strings"
)

// The title is at the head of the transcript and nowhere else:
//
//	~/.claude/projects/<slug>/<session-id>.jsonl
//	{"type":"ai-title","aiTitle":"Fix Sketchybar display on external monitors",…}
//
// It is generated by a side query — `querySource:"generate_session_title"`, a
// JSON-schema call returning `{title}` — and appended once, shortly after the
// conversation it describes begins. What it produces is the only thing on the
// machine that reads like a person named the session: "Fix Sketchybar display
// on external monitors", "Remove option-n binding from sketchybar", "Build
// terminal-based Grafana-like dashboard with Kitty graphics".
//
// [verified 2026-09-22, 2.1.267] **It is not being written at the moment.** 26
// transcripts on this machine hold one; the newest was written 2026-08-27 under
// 2.1.231 and none of the 222 written since has one. The generator is still in
// the binary, the SDK still documents a custom title as one that "skips
// automatic title generation", and other surfaces still write the line — so
// this is a path that stopped firing, not a field that went away. It is read
// anyway: it costs one open and one read of a file `usage.go` has just read
// from the other end, and the day it comes back every unnamed session is better
// named for nothing.
//
// [verified 2026-10-09, 2.1.285] Still dark. None of the 206 transcripts on
// this machine holds one — the 26 above have since been cleaned away by age —
// and an interactive session driven through a prompt wrote none.
//
// What is deliberately **not** read is the first prompt below it. It is always
// there and it says what the session is about, and it is still not a name: it
// is prose, it would have to be cut to fit anywhere, and reporting it would
// mean core could no longer tell a session nobody has named from one somebody
// did (D-75). An unnamed session reports nothing and core does the guessing.
const (
	// theHeadOfTheTranscript is how much of the beginning is read, in one call,
	// forwards.
	//
	// Forwards, which is the opposite of usage.go, because the title is written
	// at the beginning and never rewritten while the numbers are only ever at
	// the end. [verified 2026-09-22] It lands between 16.8 KiB and 23.7 KiB in
	// 18 of the 26 transcripts that have one.
	//
	// The other 8 are between 316 KiB and 2.2 MB in, at no fixed distance from
	// either end, and they are deliberately not chased: they are sessions
	// titled long after they started, the scan to reach them is unbounded, and
	// it would run on every hook of every session that has no title at all —
	// which today is all of them. A title that is missed costs the session its
	// name, and core's guess is what a missed name has always cost.
	theHeadOfTheTranscript = 64 << 10
)

// WhatClaudeTitlesThisSession is Claude's own title for it, or nothing at all.
//
// Nothing at all is the ordinary answer and never an error: a transcript that
// has not been written yet, a payload that carried no path, a session Claude
// has not titled — which today is every session. Core treats an empty name as
// "leave the stored one alone", and a session that is never named is one core
// names after its directory (§A7.4.2, D-75).
func WhatClaudeTitlesThisSession(transcriptPath string) string {
	transcriptPath = strings.TrimSpace(transcriptPath)
	if transcriptPath == "" {
		return ""
	}
	file, err := os.Open(transcriptPath)
	if err != nil {
		return ""
	}
	defer file.Close()

	head := make([]byte, theHeadOfTheTranscript)
	// A short read is the ordinary case and io.EOF the ordinary error: a
	// session a minute old is smaller than this window. Only the count matters.
	read, _ := file.ReadAt(head, 0)
	if read == 0 {
		return ""
	}
	head = head[:read]

	lines := bytes.Split(head, []byte("\n"))
	if head[read-1] != '\n' {
		// The window ended in the middle of a line, or Claude is midway through
		// appending one. Either way the last one is a fragment.
		lines = lines[:len(lines)-1]
	}
	for _, line := range lines {
		if title, itIsTheTitle := titleInLine(line); itIsTheTitle {
			return title
		}
	}
	return ""
}

// titleLine is the cheap test that decides whether a line is worth decoding.
// Most of a transcript is prompts, attachments and tool results, and one of
// them can be a megabyte long.
var titleLine = []byte(`"ai-title"`)

// headLine is the part of one line this program reads. Claude writes a dozen
// more fields on every one of them and will write more.
type headLine struct {
	Type    string `json:"type"`
	AITitle string `json:"aiTitle"`
}

// titleInLine reads one line, and says whether it is Claude's title for this
// session.
//
// Claude is appending to this file while this runs and the read may have landed
// mid-line, so a line that does not parse is ordinary and worth nothing more
// than moving on to the next one.
func titleInLine(line []byte) (string, bool) {
	if !bytes.Contains(line, titleLine) {
		return "", false
	}
	var written headLine
	if err := json.Unmarshal(line, &written); err != nil {
		return "", false
	}
	if written.Type != "ai-title" {
		return "", false
	}
	title := strings.TrimSpace(written.AITitle)
	return title, title != ""
}
